### ISSUE TITLE
Build fails [node_modules/webpack-cli/bin/cli.js:231]

### ISSUE THREAD

**Issue by mikeblackstock** [os-js/osjs-ace-application#2]
After 'npm install', and changing to installation directory, 'npm run build' gives:

osjs-ace-application/node_modules/webpack-cli/bin/cli.js:231:
Error: custom keyword definition is invalid: data/errors should be boolean

-M.
[Some day this old LAMP guy will know enough about npm,  webpack etc. to just
send a PR with the fix. I'm catching on, though,  steadily :) ]

![ace-fail](https://user-images.githubusercontent.com/223399/52527950-b0d9d980-2c9f-11e9-9d2e-ba961b6d1d1d.png)

**Comment by andersevenrud** [comment]
This is because an update of `ajv` broke webpack:

https://github.com/webpack/webpack/issues/8768

**Comment by andersevenrud** [comment]
Seems to have been resolved in: https://github.com/epoberezkin/ajv/issues/941

Try running `npm update`, then try again :)

**Comment by mikeblackstock** [comment]
Thx Anders. Indeed that thread had a solution that worked for me:
npm uninstall ajv
npm install ajv@6.8.1
